### ISSUE TITLE
Add User with Invoke 

### ISSUE THREAD

**Issue by fahmawy** [apostrophecms/apostrophe-multisite#22]
Hey bro just i am trying to add user after i create the new site in my dashboard iam using 
`      async function addUser() {
        return self.apos.tasks
          .invoke(
            "apostrophe-users:add",
            [piece.credentialArray[0].username, "admin"],
            {
              site: piece.slug
            }
          )
          .then(function(res) {
            debugger;
            console.log(res);
          })
          .catch(function(error) {
            debugger;
            console.log(error);
          });
        debugger;
      }`
after action its spin till i put the password in command line so please whats is the way to pass the password with the invoke task

**Comment by boutell** [comment]
Hi @fahmawy, you can't do that with the invoke task because this particular task is not designed to accept a password on the command line, only from standard input. However, just take a look at the source code for that task in the apostrophe-users module. Not hard to borrow it for your own use.
