### ISSUE TITLE
Sites should be able to have differing apos configurations

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe-multisite#23]

**Comment by boutell** [comment]
Currently implementation is underway in the `sites-function` branch. `sites` can be a function that takes a site object and returns an apos config object.

While quite far along, this branch has one big oversight that I know of: if two different site configurations result in two different asset sets, only the first set of assets is going to get sent, because of the way all sites share assets with multisite. 

Rebuilding assets on every startup for every site is not acceptable from a performance standpoint. 

We could simplify the problem with a theme switcher rather than allowing individual site objects to determine their own configuration via a function. However this would rule out mixing and matching features for sites, which we already know we need.

We can address this by suffixing the generationId of assets like so:

```
generationId + hash(js and css input files list)
```

“if [assets exist under that name already] then we can just reuse them”

**Comment by abea** [comment]
@boutell It looks like the `sites-function` branch is up to date with master. Is this clear to close?

**Comment by uurrnn** [comment]
Has this been completed?

**Comment by boutell** [comment]
This has been completed, there is sites function support. If you want to turn modules on and off entirely on a per-site basis in a way that impacts the asset bundle's contents, then you can do this only by changing the "theme" property of the site piece — the theme must completely determine the asset bundle's contents so we are not forced to generate an asset bundle for every individual site.
