### ISSUE TITLE
CSRF cookies SameSite attribute unset

### ISSUE THREAD

**Issue by poetaster** [apostrophecms/apostrophe-multisite#55]
Install from Git, last week.

`Cookie “multisite-ckkclehap000k3i4sxv7zp87b.csrf” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite`

## To Reproduce

Step by step instructions to reproduce the behavior:

 1. Turn on Developer Console in FF or Chrome, etc.
 2. Observe warnings.

## Expected behavior

SameSite attribute set?

## Describe the bug

The SameSite Attribute is missing.

## Details

**Version of Node.js:**

12.20.1

**Server Operating System:**

Debian Buster

**Comment by poetaster** [comment]
A note, I'm using the museum demo as a template within sites. I'm not sure if that might be related.

**Comment by boutell** [comment]
This is a more general apostrophe issue not specific to the multisite module. Would you mind reopening on apostrophe?
